[package]
name = "build_details"
version = "0.1.0"
authors = ["Sam Wilson <tecywiz121@hotmail.com>"]

[workspace]
members = [
    "test_crate"
]

[dependencies]
maplit = "1.0.1"
phf_codegen = "0.7.22"

[dev-dependencies]
tempfile = "3.0.3"
lazy_static = "1.0.0"
